version: '3'
services:
  frontend-example:
    image: frontend-example
    ports:
      - 5000:5000
    #container_name: frontend-example
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  backend-example:
    image: backend-example
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=postgres
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/usr/src/backend-example/logs.txt
    #container_name: backend-example
  redis:
    image: redis
