version: '3'
services:
  frontend-example:
    image: frontend-example
    ports:
      - 5000:5000
    environment:
      - API_URL=http://192.168.99.103/api
    #container_name: frontend-example
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  backend-example:
    image: backend-example
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=postgres
      - FRONT_URL=http://192.168.99.103
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/usr/src/backend-example/logs.txt
    #container_name: backend-example
  redis:
    image: redis
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
